CREATE TYPE public.app_role AS ENUM ('admin', 'coach', 'member');
CREATE TYPE public.member_status AS ENUM ('active', 'inactive', 'frozen', 'expired', 'lead');
CREATE TYPE public.membership_status AS ENUM ('pending', 'active', 'frozen', 'expired', 'cancelled');
CREATE TYPE public.payment_status AS ENUM ('created', 'pending', 'verified', 'failed', 'refunded', 'partially_refunded');
CREATE TYPE public.payment_method AS ENUM ('razorpay', 'cash', 'upi', 'bank_transfer', 'card_recorded');
CREATE TYPE public.booking_status AS ENUM ('booked', 'cancelled', 'attended', 'no_show');
CREATE TYPE public.access_decision AS ENUM ('granted', 'denied');

CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY,
  email text NOT NULL,
  display_name text NOT NULL DEFAULT '',
  phone text,
  avatar_url text,
  date_of_birth date,
  gender text,
  address text,
  emergency_contact_name text,
  emergency_contact_phone text,
  medical_notes text,
  fitness_goals text,
  preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role public.app_role NOT NULL DEFAULT 'member',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id, role)
);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role) $$;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;

CREATE POLICY profiles_own_read ON public.profiles FOR SELECT TO authenticated USING (id = auth.uid() OR public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'coach'));
CREATE POLICY profiles_own_update ON public.profiles FOR UPDATE TO authenticated USING (id = auth.uid() OR public.has_role(auth.uid(), 'admin')) WITH CHECK (id = auth.uid() OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY profiles_own_insert ON public.profiles FOR INSERT TO authenticated WITH CHECK (id = auth.uid() OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY roles_own_read ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.has_role(auth.uid(), 'admin'));

CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN INSERT INTO public.profiles (id,email,display_name,avatar_url) VALUES (NEW.id, COALESCE(NEW.email,''), COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(COALESCE(NEW.email,''),'@',1)), NEW.raw_user_meta_data->>'avatar_url'); INSERT INTO public.user_roles(user_id,role) VALUES (NEW.id,'member'); RETURN NEW; END; $$;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
CREATE TRIGGER profiles_updated BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), profile_id uuid UNIQUE NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, member_code text UNIQUE NOT NULL, status public.member_status NOT NULL DEFAULT 'lead', joined_on date, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.members TO authenticated; GRANT ALL ON public.members TO service_role; ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
CREATE POLICY members_read ON public.members FOR SELECT TO authenticated USING (profile_id=auth.uid() OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach'));
CREATE POLICY members_admin_write ON public.members FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE TRIGGER members_updated BEFORE UPDATE ON public.members FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.trainers (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), profile_id uuid UNIQUE NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, specialties text[] NOT NULL DEFAULT '{}', certifications text[] NOT NULL DEFAULT '{}', bio text, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
); GRANT SELECT, INSERT, UPDATE, DELETE ON public.trainers TO authenticated; GRANT ALL ON public.trainers TO service_role; ALTER TABLE public.trainers ENABLE ROW LEVEL SECURITY;
CREATE POLICY trainers_read ON public.trainers FOR SELECT TO authenticated USING (true);
CREATE POLICY trainers_admin_write ON public.trainers FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE TRIGGER trainers_updated BEFORE UPDATE ON public.trainers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.membership_plans (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, description text, duration_days int NOT NULL CHECK(duration_days>0), price_inr numeric(12,2) NOT NULL CHECK(price_inr>=0), joining_fee_inr numeric(12,2) NOT NULL DEFAULT 0, class_limit int, freeze_days int NOT NULL DEFAULT 0, benefits text[] NOT NULL DEFAULT '{}', active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
); GRANT SELECT ON public.membership_plans TO authenticated; GRANT INSERT,UPDATE,DELETE ON public.membership_plans TO authenticated; GRANT ALL ON public.membership_plans TO service_role; ALTER TABLE public.membership_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY plans_read ON public.membership_plans FOR SELECT TO authenticated USING (true); CREATE POLICY plans_admin_write ON public.membership_plans FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin')); CREATE TRIGGER plans_updated BEFORE UPDATE ON public.membership_plans FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.memberships (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), member_id uuid NOT NULL REFERENCES public.members(id) ON DELETE CASCADE, plan_id uuid NOT NULL REFERENCES public.membership_plans(id), status public.membership_status NOT NULL DEFAULT 'pending', starts_on date NOT NULL, ends_on date NOT NULL, frozen_from date, frozen_until date, cancelled_at timestamptz, auto_renew boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(ends_on>=starts_on), CHECK(frozen_until IS NULL OR frozen_from IS NOT NULL)
); GRANT SELECT,INSERT,UPDATE,DELETE ON public.memberships TO authenticated; GRANT ALL ON public.memberships TO service_role; ALTER TABLE public.memberships ENABLE ROW LEVEL SECURITY;
CREATE POLICY memberships_read ON public.memberships FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.members m WHERE m.id=member_id AND m.profile_id=auth.uid()) OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach'));
CREATE POLICY memberships_admin_write ON public.memberships FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin')); CREATE TRIGGER memberships_updated BEFORE UPDATE ON public.memberships FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.payments (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), member_id uuid NOT NULL REFERENCES public.members(id), membership_id uuid REFERENCES public.memberships(id), amount_inr numeric(12,2) NOT NULL CHECK(amount_inr>0), method public.payment_method NOT NULL, status public.payment_status NOT NULL DEFAULT 'created', provider_order_id text UNIQUE, provider_payment_id text UNIQUE, receipt_number text UNIQUE, refund_amount_inr numeric(12,2) NOT NULL DEFAULT 0, verified_at timestamptz, paid_at timestamptz, notes text, created_by uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
); GRANT SELECT,INSERT,UPDATE ON public.payments TO authenticated; GRANT ALL ON public.payments TO service_role; ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY payments_read ON public.payments FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.members m WHERE m.id=member_id AND m.profile_id=auth.uid()) OR public.has_role(auth.uid(),'admin'));
CREATE POLICY payments_admin_write ON public.payments FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin')); CREATE TRIGGER payments_updated BEFORE UPDATE ON public.payments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.payment_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), payment_id uuid REFERENCES public.payments(id), provider_event_id text UNIQUE NOT NULL, event_type text NOT NULL, payload jsonb NOT NULL DEFAULT '{}'::jsonb, processed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()); GRANT SELECT ON public.payment_events TO authenticated; GRANT ALL ON public.payment_events TO service_role; ALTER TABLE public.payment_events ENABLE ROW LEVEL SECURITY; CREATE POLICY payment_events_admin ON public.payment_events FOR SELECT TO authenticated USING (public.has_role(auth.uid(),'admin'));

CREATE TABLE public.classes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, description text, category text NOT NULL, difficulty text NOT NULL DEFAULT 'all-levels', default_capacity int NOT NULL CHECK(default_capacity>0), duration_minutes int NOT NULL CHECK(duration_minutes>0), active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()); GRANT SELECT,INSERT,UPDATE,DELETE ON public.classes TO authenticated; GRANT ALL ON public.classes TO service_role; ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY; CREATE POLICY classes_read ON public.classes FOR SELECT TO authenticated USING (true); CREATE POLICY classes_staff_write ON public.classes FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')); CREATE TRIGGER classes_updated BEFORE UPDATE ON public.classes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.class_schedules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), class_id uuid NOT NULL REFERENCES public.classes(id), trainer_id uuid REFERENCES public.trainers(id), starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, capacity int NOT NULL CHECK(capacity>0), cancellation_deadline_minutes int NOT NULL DEFAULT 120, status text NOT NULL DEFAULT 'scheduled', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(ends_at>starts_at)); GRANT SELECT,INSERT,UPDATE,DELETE ON public.class_schedules TO authenticated; GRANT ALL ON public.class_schedules TO service_role; ALTER TABLE public.class_schedules ENABLE ROW LEVEL SECURITY; CREATE POLICY schedules_read ON public.class_schedules FOR SELECT TO authenticated USING (true); CREATE POLICY schedules_staff_write ON public.class_schedules FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')); CREATE TRIGGER schedules_updated BEFORE UPDATE ON public.class_schedules FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.class_bookings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), schedule_id uuid NOT NULL REFERENCES public.class_schedules(id) ON DELETE CASCADE, member_id uuid NOT NULL REFERENCES public.members(id) ON DELETE CASCADE, status public.booking_status NOT NULL DEFAULT 'booked', booked_at timestamptz NOT NULL DEFAULT now(), cancelled_at timestamptz, UNIQUE(schedule_id,member_id)); GRANT SELECT,INSERT,UPDATE,DELETE ON public.class_bookings TO authenticated; GRANT ALL ON public.class_bookings TO service_role; ALTER TABLE public.class_bookings ENABLE ROW LEVEL SECURITY; CREATE POLICY bookings_read ON public.class_bookings FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.members m WHERE m.id=member_id AND m.profile_id=auth.uid()) OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')); CREATE POLICY bookings_own_insert ON public.class_bookings FOR INSERT TO authenticated WITH CHECK (EXISTS(SELECT 1 FROM public.members m WHERE m.id=member_id AND m.profile_id=auth.uid()) OR public.has_role(auth.uid(),'admin')); CREATE POLICY bookings_own_update ON public.class_bookings FOR UPDATE TO authenticated USING (EXISTS(SELECT 1 FROM public.members m WHERE m.id=member_id AND m.profile_id=auth.uid()) OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')) WITH CHECK (EXISTS(SELECT 1 FROM public.members m WHERE m.id=member_id AND m.profile_id=auth.uid()) OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach'));

CREATE TABLE public.class_waitlists (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), schedule_id uuid NOT NULL REFERENCES public.class_schedules(id) ON DELETE CASCADE, member_id uuid NOT NULL REFERENCES public.members(id) ON DELETE CASCADE, position int NOT NULL CHECK(position>0), joined_at timestamptz NOT NULL DEFAULT now(), promoted_at timestamptz, UNIQUE(schedule_id,member_id)); GRANT SELECT,INSERT,DELETE ON public.class_waitlists TO authenticated; GRANT ALL ON public.class_waitlists TO service_role; ALTER TABLE public.class_waitlists ENABLE ROW LEVEL SECURITY; CREATE POLICY waitlists_read ON public.class_waitlists FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.members m WHERE m.id=member_id AND m.profile_id=auth.uid()) OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')); CREATE POLICY waitlists_own_insert ON public.class_waitlists FOR INSERT TO authenticated WITH CHECK (EXISTS(SELECT 1 FROM public.members m WHERE m.id=member_id AND m.profile_id=auth.uid()) OR public.has_role(auth.uid(),'admin')); CREATE POLICY waitlists_own_delete ON public.class_waitlists FOR DELETE TO authenticated USING (EXISTS(SELECT 1 FROM public.members m WHERE m.id=member_id AND m.profile_id=auth.uid()) OR public.has_role(auth.uid(),'admin'));

CREATE TABLE public.workouts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, workout_date date NOT NULL, stimulus text, description text NOT NULL, scoring_type text NOT NULL DEFAULT 'time', time_cap_minutes int, scaling_notes text, published boolean NOT NULL DEFAULT false, created_by uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workout_date,title)); GRANT SELECT,INSERT,UPDATE,DELETE ON public.workouts TO authenticated; GRANT ALL ON public.workouts TO service_role; ALTER TABLE public.workouts ENABLE ROW LEVEL SECURITY; CREATE POLICY workouts_read ON public.workouts FOR SELECT TO authenticated USING (published OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')); CREATE POLICY workouts_staff_write ON public.workouts FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')); CREATE TRIGGER workouts_updated BEFORE UPDATE ON public.workouts FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.workout_exercises (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workout_id uuid NOT NULL REFERENCES public.workouts(id) ON DELETE CASCADE, exercise_name text NOT NULL, sequence int NOT NULL, prescription text NOT NULL, movement_standard text); GRANT SELECT,INSERT,UPDATE,DELETE ON public.workout_exercises TO authenticated; GRANT ALL ON public.workout_exercises TO service_role; ALTER TABLE public.workout_exercises ENABLE ROW LEVEL SECURITY; CREATE POLICY exercises_read ON public.workout_exercises FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.workouts w WHERE w.id=workout_id AND (w.published OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')))); CREATE POLICY exercises_staff_write ON public.workout_exercises FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach'));

CREATE TABLE public.workout_results (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workout_id uuid NOT NULL REFERENCES public.workouts(id) ON DELETE CASCADE, member_id uuid NOT NULL REFERENCES public.members(id) ON DELETE CASCADE, score text NOT NULL, rx boolean NOT NULL DEFAULT false, notes text, recorded_by uuid, recorded_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workout_id,member_id)); GRANT SELECT,INSERT,UPDATE ON public.workout_results TO authenticated; GRANT ALL ON public.workout_results TO service_role; ALTER TABLE public.workout_results ENABLE ROW LEVEL SECURITY; CREATE POLICY results_read ON public.workout_results FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.members m WHERE m.id=member_id AND m.profile_id=auth.uid()) OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')); CREATE POLICY results_write ON public.workout_results FOR ALL TO authenticated USING (EXISTS(SELECT 1 FROM public.members m WHERE m.id=member_id AND m.profile_id=auth.uid()) OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')) WITH CHECK (EXISTS(SELECT 1 FROM public.members m WHERE m.id=member_id AND m.profile_id=auth.uid()) OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach'));

CREATE TABLE public.attendance (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), member_id uuid NOT NULL REFERENCES public.members(id), schedule_id uuid REFERENCES public.class_schedules(id), checked_in_at timestamptz NOT NULL DEFAULT now(), source text NOT NULL DEFAULT 'manual', external_event_id text UNIQUE, recorded_by uuid, created_at timestamptz NOT NULL DEFAULT now()); GRANT SELECT,INSERT,UPDATE ON public.attendance TO authenticated; GRANT ALL ON public.attendance TO service_role; ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY; CREATE POLICY attendance_read ON public.attendance FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.members m WHERE m.id=member_id AND m.profile_id=auth.uid()) OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')); CREATE POLICY attendance_staff_write ON public.attendance FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach'));

CREATE TABLE public.access_devices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, vendor text NOT NULL, device_type text NOT NULL, external_id text UNIQUE, location text, active boolean NOT NULL DEFAULT true, last_seen_at timestamptz, configuration jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()); GRANT SELECT,INSERT,UPDATE,DELETE ON public.access_devices TO authenticated; GRANT ALL ON public.access_devices TO service_role; ALTER TABLE public.access_devices ENABLE ROW LEVEL SECURITY; CREATE POLICY devices_admin ON public.access_devices FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin')); CREATE TRIGGER devices_updated BEFORE UPDATE ON public.access_devices FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TABLE public.access_credentials (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), member_id uuid NOT NULL REFERENCES public.members(id) ON DELETE CASCADE, credential_type text NOT NULL, external_reference text UNIQUE NOT NULL, label text, active boolean NOT NULL DEFAULT true, registered_at timestamptz NOT NULL DEFAULT now(), revoked_at timestamptz); GRANT SELECT,INSERT,UPDATE,DELETE ON public.access_credentials TO authenticated; GRANT ALL ON public.access_credentials TO service_role; ALTER TABLE public.access_credentials ENABLE ROW LEVEL SECURITY; CREATE POLICY credentials_read ON public.access_credentials FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.members m WHERE m.id=member_id AND m.profile_id=auth.uid()) OR public.has_role(auth.uid(),'admin')); CREATE POLICY credentials_admin_write ON public.access_credentials FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE TABLE public.access_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), device_id uuid REFERENCES public.access_devices(id), credential_id uuid REFERENCES public.access_credentials(id), member_id uuid REFERENCES public.members(id), external_event_id text UNIQUE NOT NULL, decision public.access_decision NOT NULL, reason text, occurred_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now()); GRANT SELECT ON public.access_events TO authenticated; GRANT ALL ON public.access_events TO service_role; ALTER TABLE public.access_events ENABLE ROW LEVEL SECURITY; CREATE POLICY access_events_read ON public.access_events FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.members m WHERE m.id=member_id AND m.profile_id=auth.uid()) OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'coach'));

CREATE TABLE public.trainer_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), trainer_id uuid NOT NULL REFERENCES public.trainers(id) ON DELETE CASCADE, schedule_id uuid NOT NULL REFERENCES public.class_schedules(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(trainer_id,schedule_id)); GRANT SELECT,INSERT,DELETE ON public.trainer_assignments TO authenticated; GRANT ALL ON public.trainer_assignments TO service_role; ALTER TABLE public.trainer_assignments ENABLE ROW LEVEL SECURITY; CREATE POLICY assignments_read ON public.trainer_assignments FOR SELECT TO authenticated USING (true); CREATE POLICY assignments_admin_write ON public.trainer_assignments FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

CREATE TABLE public.notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, title text NOT NULL, message text NOT NULL, category text NOT NULL DEFAULT 'general', read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()); GRANT SELECT,UPDATE ON public.notifications TO authenticated; GRANT ALL ON public.notifications TO service_role; ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY; CREATE POLICY notifications_own_read ON public.notifications FOR SELECT TO authenticated USING (user_id=auth.uid() OR public.has_role(auth.uid(),'admin')); CREATE POLICY notifications_own_update ON public.notifications FOR UPDATE TO authenticated USING (user_id=auth.uid()) WITH CHECK (user_id=auth.uid());
CREATE TABLE public.gym_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), gym_name text NOT NULL DEFAULT 'Forge Functional Fitness', timezone text NOT NULL DEFAULT 'Asia/Kolkata', currency text NOT NULL DEFAULT 'INR', booking_window_days int NOT NULL DEFAULT 14, default_cancellation_minutes int NOT NULL DEFAULT 120, contact_email text, contact_phone text, address text, updated_at timestamptz NOT NULL DEFAULT now()); GRANT SELECT,UPDATE ON public.gym_settings TO authenticated; GRANT ALL ON public.gym_settings TO service_role; ALTER TABLE public.gym_settings ENABLE ROW LEVEL SECURITY; CREATE POLICY settings_read ON public.gym_settings FOR SELECT TO authenticated USING (true); CREATE POLICY settings_admin_write ON public.gym_settings FOR UPDATE TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin')); CREATE TRIGGER settings_updated BEFORE UPDATE ON public.gym_settings FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TABLE public.audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_id uuid, action text NOT NULL, entity_type text NOT NULL, entity_id uuid, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, ip_address inet, created_at timestamptz NOT NULL DEFAULT now()); GRANT SELECT ON public.audit_logs TO authenticated; GRANT ALL ON public.audit_logs TO service_role; ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY; CREATE POLICY audits_admin_read ON public.audit_logs FOR SELECT TO authenticated USING (public.has_role(auth.uid(),'admin'));

CREATE INDEX idx_members_status ON public.members(status); CREATE INDEX idx_memberships_member_status ON public.memberships(member_id,status); CREATE INDEX idx_schedules_starts ON public.class_schedules(starts_at); CREATE INDEX idx_bookings_schedule_status ON public.class_bookings(schedule_id,status); CREATE INDEX idx_attendance_member_time ON public.attendance(member_id,checked_in_at DESC); CREATE INDEX idx_access_events_time ON public.access_events(occurred_at DESC); CREATE INDEX idx_payments_member_status ON public.payments(member_id,status); CREATE INDEX idx_notifications_user_unread ON public.notifications(user_id,read_at);

INSERT INTO public.membership_plans(name,description,duration_days,price_inr,joining_fee_inr,freeze_days,benefits) VALUES ('Foundation','Unlimited group classes and progress tracking',30,3499,499,3,ARRAY['Unlimited classes','WOD tracking','Open gym']),('Performance','Coaching support with extended freeze flexibility',90,8999,0,10,ARRAY['Unlimited classes','Monthly coach review','10 freeze days']),('Annual Athlete','Best value for committed athletes',365,29999,0,30,ARRAY['Unlimited classes','Quarterly assessment','30 freeze days','Priority booking']);
INSERT INTO public.classes(name,description,category,difficulty,default_capacity,duration_minutes) VALUES ('CrossFit','Strength and conditioning with a coached daily workout','CrossFit','all-levels',18,60),('Engine Room','Interval conditioning across rower, bike, and ski','Conditioning','intermediate',16,50),('Barbell Club','Technique and strength work for Olympic lifts','Weightlifting','intermediate',12,75),('Mobility Reset','Guided mobility and recovery session','Recovery','all-levels',20,45);
INSERT INTO public.gym_settings(gym_name,timezone,currency,contact_email) VALUES ('Forge Functional Fitness','Asia/Kolkata','INR','hello@forgefit.example');