CREATE TABLE IF NOT EXISTS public.gym_drive_archive_oauth (
  id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  client_id text NOT NULL,
  client_secret_ciphertext text NOT NULL,
  refresh_token_ciphertext text,
  sender_email text,
  folder_id text,
  folder_url text,
  connected_at timestamptz,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.gym_drive_archive_oauth ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.gym_drive_archive_oauth FROM anon, authenticated;
GRANT ALL ON TABLE public.gym_drive_archive_oauth TO service_role;

CREATE TABLE IF NOT EXISTS public.gym_data_archive_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  archive_date date NOT NULL,
  dataset text NOT NULL CHECK (dataset IN ('attendance', 'class_bookings')),
  drive_file_id text NOT NULL,
  drive_file_name text NOT NULL,
  row_count integer NOT NULL DEFAULT 0 CHECK (row_count >= 0),
  exported_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (archive_date, dataset)
);

ALTER TABLE public.gym_data_archive_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.gym_data_archive_runs FROM anon, authenticated;
GRANT ALL ON TABLE public.gym_data_archive_runs TO service_role;
